In [6]:
chr(0)

'\x00'

In [7]:
print(chr(0))




In [8]:
"this is a test" + chr(0) + "string"

'this is a test\x00string'

In [9]:
print("this is a test" + chr(0) + "string")

this is a teststring


In [11]:
test_string = "hello! こんにちは!"
utf8_encoded = test_string.encode("utf-8")
utf16_encoded = test_string.encode("utf-16")
utf32_encoded = test_string.encode("utf-32")
print('utf8: ', utf8_encoded)
print('utf16:', utf16_encoded)
print('utf32:', utf32_encoded)
print('utf8: ', list(utf8_encoded))
print('utf16:', list(utf16_encoded))
print('utf32:', list(utf32_encoded))
print(len(test_string))
print('utf8: ', len(utf8_encoded))
print('utf16:', len(utf16_encoded))
print('utf32:', len(utf32_encoded))


utf8:  b'hello! \xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf!'
utf16: b'\xff\xfeh\x00e\x00l\x00l\x00o\x00!\x00 \x00S0\x930k0a0o0!\x00'
utf32: b'\xff\xfe\x00\x00h\x00\x00\x00e\x00\x00\x00l\x00\x00\x00l\x00\x00\x00o\x00\x00\x00!\x00\x00\x00 \x00\x00\x00S0\x00\x00\x930\x00\x00k0\x00\x00a0\x00\x00o0\x00\x00!\x00\x00\x00'
utf8:  [104, 101, 108, 108, 111, 33, 32, 227, 129, 147, 227, 130, 147, 227, 129, 171, 227, 129, 161, 227, 129, 175, 33]
utf16: [255, 254, 104, 0, 101, 0, 108, 0, 108, 0, 111, 0, 33, 0, 32, 0, 83, 48, 147, 48, 107, 48, 97, 48, 111, 48, 33, 0]
utf32: [255, 254, 0, 0, 104, 0, 0, 0, 101, 0, 0, 0, 108, 0, 0, 0, 108, 0, 0, 0, 111, 0, 0, 0, 33, 0, 0, 0, 32, 0, 0, 0, 83, 48, 0, 0, 147, 48, 0, 0, 107, 48, 0, 0, 97, 48, 0, 0, 111, 48, 0, 0, 33, 0, 0, 0]
13
utf8:  23
utf16: 28
utf32: 56


In [16]:
def decode_utf8_bytes_to_str_wrong(bytestring: bytes):
    print(bytestring)
    return "".join([bytes([b]).decode("utf-8") for b in bytestring])

In [17]:
decode_utf8_bytes_to_str_wrong("你好".encode("utf-8"))

b'\xe4\xbd\xa0\xe5\xa5\xbd'


UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 0: unexpected end of data

In [15]:
"你好".encode("utf-8").decode("utf-8")

'你好'

lo:7 ow:7 we:2 er:2 wi:3 id:3 dest:3 ne:6 ew:6 west:6
ow
low:7 owe:2 er:2 wi:3 id:3 dest:3 ne:6 ew:6 west:6
low
lowe:2 er:2 wi:3 id:3 dest:3 ne:6 ew:6 west:6
west
lowe:2 er:2 wi:3 id:3 dest:3 ne:6 ewest:6
ne
lowe:2 er:2 wi:3 id:3 dest:3 newest:6
newest
lowe:2 er:2 wi:3 id:3 dest:3
wi
lowe:2 er:2 wid:3 dest:3
wid
lowe:2 er:2 widest:3
widest
lowe:2 er:2
lowe
lower:2
lower


In [2]:
import multiprocessing
multiprocessing.cpu_count()

28

In [3]:
1761807291.789897 - 1761807290.125814

1.6640830039978027

In [1]:
def to_bytes_tuple(word: str):
    return tuple(bytes([b]) for b in word.encode("utf-8"))

In [2]:
to_bytes_tuple("hello")

(b'h', b'e', b'l', b'l', b'o')

In [4]:
a = [1, 5, 20, 18, 10, 200]
a = list(map(lambda x:-x,a))
a

[-1, -5, -20, -18, -10, -200]

In [8]:
a = tuple(bytes([b]) for b in 'hello'.encode('utf-8'))
a[0]

b'h'

In [2]:
import torch
print(torch.cuda.is_available())
print("CUDA Version:", torch.version.cuda)
print(torch.__version__)

True
CUDA Version: 12.4
2.5.1


In [23]:
import regex

In [24]:

test_string = "Héllò hôw <|endoftext|><|endoftext|> are ü? 🙃<|endoftext|>"
special_tokens = ["<|endoftext|>"]
special_tokens_pattern = '|'.join(special_tokens)
sorted_special_tokens = sorted(special_tokens, key=len, reverse=True)
special_tokens_pattern = '|'.join(map(regex.escape, sorted_special_tokens))
# 使用捕获组，这样分隔符也会包含在结果中
pattern_with_capture = f'({special_tokens_pattern})'
for sub_text in regex.split(pattern_with_capture, test_string):
    print(f"Sub-text: '{sub_text}'")

Sub-text: 'Héllò hôw '
Sub-text: '<|endoftext|>'
Sub-text: ''
Sub-text: '<|endoftext|>'
Sub-text: ' are ü? 🙃'
Sub-text: '<|endoftext|>'
Sub-text: ''


In [25]:
import torch
import numpy as np

In [26]:
a = torch.arange(9).reshape(3, 3)
print(a)
# i = 3
torch_ein_out = torch.einsum('ii->i', [a]).numpy()
print(torch_ein_out)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
[0 4 8]


In [27]:
a = torch.arange(6).reshape(2, 3)
# i = 2, j = 3
torch_ein_out = torch.einsum('ij->ji', [a]).numpy()
print(torch_ein_out)

[[0 3]
 [1 4]
 [2 5]]


In [28]:
a = torch.arange(6).reshape(2, 3)
print(a)
# i = 2, j = 3
torch_ein_out = torch.einsum('ij->', [a]).numpy()
print(torch_ein_out)

tensor([[0, 1, 2],
        [3, 4, 5]])
15


In [29]:
a = torch.arange(6).reshape(2, 3)
# i = 2, j = 3
torch_ein_out = torch.einsum('ij->j', [a]).numpy()
print(torch_ein_out)

[3 5 7]


In [30]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(3)
print(b)
# i = 2, k = 3
torch_ein_out = torch.einsum('ik,k->i', [a, b]).numpy()
# 等价形式，可以省略箭头和输出
torch_ein_out2 = torch.einsum('ik,k', [a, b]).numpy()
print(torch_ein_out)
print(torch_ein_out2)

tensor([0, 1, 2])
[ 5 14]
[ 5 14]


In [31]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)
# i = 2, k = 3, j = 5
torch_ein_out = torch.einsum('ik,kj->ij', [a, b]).numpy()
# 等价形式，可以省略箭头和输出
torch_ein_out2 = torch.einsum('ik,kj', [a, b]).numpy() 
print(torch_ein_out)
print(torch_ein_out2)

[[ 25  28  31  34  37]
 [ 70  82  94 106 118]]
[[ 25  28  31  34  37]
 [ 70  82  94 106 118]]


In [32]:
a = torch.arange(3)
b = torch.arange(3, 6) # [3, 4, 5]
print(a)
print(b)
# i = 3
torch_ein_out = torch.einsum('i,i->', [a, b]).numpy()
# 等价形式，可以省略箭头和输出
torch_ein_out2 = torch.einsum('i,i', [a, b]).numpy()
print(torch_ein_out)
print(torch_ein_out2)

tensor([0, 1, 2])
tensor([3, 4, 5])
14
14


In [33]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
# i = 2, j = 3
torch_ein_out = torch.einsum('ij,ij->', [a, b]).numpy()
# 等价形式，可以省略箭头和输出
torch_ein_out2 = torch.einsum('ij,ij', [a, b]).numpy()
print(torch_ein_out)

145


In [34]:
a = torch.arange(3)
b = torch.arange(3,7)  # [3, 4, 5, 6]
# i = 3, j = 4
torch_ein_out = torch.einsum('i,j->ij', [a, b]).numpy()
# 等价形式，可以省略箭头和输出
torch_ein_out2 = torch.einsum('i,j', [a, b]).numpy()
print(torch_ein_out)

[[ 0  0  0  0]
 [ 3  4  5  6]
 [ 6  8 10 12]]


In [35]:
a = torch.randn(2,3,5)
b = torch.randn(2,5,4)
# i = 2, j = 3, k = 5, l = 4
torch_ein_out = torch.einsum('ijk,ikl->ijl', [a, b]).numpy()
print(torch_ein_out.shape)

(2, 3, 4)


In [36]:
a = torch.randn(2,3,5,7)
b = torch.randn(11,13,3,17,5)
# p = 2, q = 3, r = 5, s = 7
# t = 11, u = 13, v = 17, r = 5
torch_ein_out = torch.einsum('pqrs,tuqvr->pstuv', [a, b]).numpy()
print(torch_ein_out.shape)

(2, 7, 11, 13, 17)


In [37]:
a = torch.randn(2,3)
b = torch.randn(5,3,7)
c = torch.randn(2,7)
# i = 2, k = 3, j = 5, l = 7
torch_ein_out = torch.einsum('ik,jkl,il->ij', [a, b, c]).numpy()
print(torch_ein_out.shape)

(2, 5)


In [39]:
import torch 
from einops import rearrange, einsum

In [40]:
images = torch.randn(64, 128, 128, 3) # (batch, height, width, channel)
dim_by = torch.linspace(start=0.0, end=1.0, steps=10)
dim_value = rearrange(dim_by, "dim_value -> 1 dim_value 1 1 1")
images_rearr = rearrange(images, "b height width channel -> b 1 height width channel")
dimmed_images = images_rearr * dim_value
dimmed_images = einsum( images, dim_by, "batch height width channel, dim_value -> batch dim_value height width channel" )

In [43]:
print(dim_by.shape, dim_value.shape)
print(images_rearr.shape, dimmed_images.shape)

torch.Size([10]) torch.Size([1, 10, 1, 1, 1])
torch.Size([64, 1, 128, 128, 3]) torch.Size([64, 10, 128, 128, 3])


In [44]:
channels_last = torch.randn(64, 32, 32, 3)
B = torch.randn(32*32, 32*32)
channels_last_flat = channels_last.view( -1, channels_last.size(1) * channels_last.size(2), channels_last.size(3))
channels_first_flat = channels_last_flat.transpose(1, 2)
channels_first_flat_transformed = channels_first_flat @ B.T
print(channels_first_flat_transformed.shape)

torch.Size([64, 3, 1024])


In [5]:
import torch
from jaxtyping import Float, Int
from torch import Tensor

In [6]:
class RMSNormModule(torch.nn.Module):
    def __init__(self, d_model: int, eps: float = 1e-5, device=None, dtype=None):
        super().__init__()
        self.d_model = d_model
        self.eps = eps
        self.weight = torch.nn.Parameter(torch.ones(d_model, device=device, dtype=dtype))
        
    def forward(self, in_features: Float[Tensor, " ... d_model"]) -> torch.Tensor:
        in_dtype = in_features.dtype
        in_features = in_features.to(torch.float32)
        norm_x = in_features.norm(p=2, dim=-1, keepdim=True)
        rms_x = norm_x / (self.d_model ** 0.5)
        return ((self.weight * in_features) / (rms_x + self.eps)).to(in_dtype)

In [10]:
rmsnorm = RMSNormModule(d_model=5)
input_tensor = torch.randn(2, 3, 5)
rmsnorm_output = rmsnorm(input_tensor)
print(rmsnorm_output)

tensor([[[ 1.3401, -0.6913, -1.2178, -1.0017, -0.4894],
         [ 0.3530, -0.7649, -0.1467, -1.7567,  1.0875],
         [-0.0666, -0.1406, -2.0587,  0.0028,  0.8586]],

        [[ 1.5458,  0.2845, -0.3042, -0.4928,  1.4812],
         [ 1.0064, -1.7060, -0.2677, -0.9857,  0.1825],
         [ 0.0454,  1.4835,  0.1101, -0.2724, -1.6464]]],
       grad_fn=<DivBackward0>)


In [14]:
from einops import rearrange

x = torch.randn((32,3,224,224)) # [B,C,H,W]
b, c, h, w = x.shape

# pytorch
ln = torch.nn.LayerNorm([c,h,w], eps=1e-12, elementwise_affine=False)
# elementwise_affine=False 关闭映射
y = ln(x)

# 为了方便理解，这里使用了einops库实现
x_ = rearrange(x, 'b c h w -> (h w c) b')
print(x_.shape)  # (h w c)  b
print(x_.mean(dim=0).shape)  # b
mean = rearrange(x_.mean(dim=0), 'b -> b 1 1 1')
std = rearrange(x_.std(dim=0), 'b -> b 1 1 1')

y_ = (x-mean)/std

# 输出差别
print('diff={}'.format(torch.abs(y-y_).max()))
# diff=2.384185791015625e-05



torch.Size([150528, 32])
torch.Size([32])
diff=1.71661376953125e-05


In [21]:
import torch
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])
b = torch.Tensor([[0, 1, 1], [1, 0, 0]]).to(torch.int64)
a[b]

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [4., 5., 6.]],

        [[4., 5., 6.],
         [1., 2., 3.],
         [1., 2., 3.]]])

In [33]:
x = torch.tensor([[[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]],
                  [[7.0, 8.0, 9.0],
                   [10.0, 11.0, 12.0]]])
x_max = x.max(dim=0, keepdim=True).values
x_max

tensor([[[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [37]:
torch.sum(x, dim=2, keepdim=True)

tensor([[[ 6.],
         [15.]],

        [[24.],
         [33.]]])

In [9]:
from jaxtyping import Float, Bool
import torch
from torch import Tensor
from einops import einsum, rearrange
class ScaledDotProductAttention(torch.nn.Module):
    def __init__(self, d_v, device=None, dtype=None):
        super().__init__()
        self.d_v = d_v
        
    def forward(self, Q: Float[Tensor, " ... queries d_k"],
                K: Float[Tensor, " ... keys d_k"],
                V: Float[Tensor, " ... values d_v"],
                mask: Bool[Tensor, " ... queries keys"] | None = None) -> torch.Tensor:
        d_k = self.d_v
        scores = einsum(Q, K, "... queries d_k, ... keys d_k -> ... queries keys") / (d_k ** 0.5)
        if mask is not None:
            scores = scores.masked_fill(~mask, float('-inf'))
        attn_weights = torch.softmax(scores, dim=-1)
        output = einsum(attn_weights, V, "... queries keys, ... keys d_v -> ... queries d_v")
        print(output.shape)
        return scores, output
    
class CausalMultiHeadAttention(torch.nn.Module):
    def __init__(self, d_model: int, num_heads: int):
        super().__init__()
        self.d_model = d_model
        self.num_heads = num_heads
        self.head_dim = d_model // num_heads
        self.scaled_dot_product_attention = ScaledDotProductAttention(d_model)
        
    def forward(self, q_proj_weight: Float[Tensor, " d_k d_in"],
                k_proj_weight: Float[Tensor, " d_k d_in"],
                v_proj_weight: Float[Tensor, " d_v d_in"],
                o_proj_weight: Float[Tensor, " d_model d_v"],
                in_features: Float[Tensor, " ... sequence_length d_in"],) -> Float[Tensor, " ... sequence_length d_out"]:
        q = einsum(in_features, q_proj_weight, "... sequence_length d_in, d_k d_in -> ... sequence_length d_k")
        k = einsum(in_features, k_proj_weight, "... sequence_length d_in, d_k d_in -> ... sequence_length d_k")
        v = einsum(in_features, v_proj_weight, "... sequence_length d_in, d_v d_in -> ... sequence_length d_v")
        
        q = rearrange(q, " ... sequence_length (num_heads head_dim) ->  ... sequence_length num_heads head_dim", num_heads=self.num_heads)
        k = rearrange(k, " ... sequence_length (num_heads head_dim) ->  ... sequence_length num_heads head_dim", num_heads=self.num_heads)
        v = rearrange(v, " ... sequence_length (num_heads head_dim) ->  ... sequence_length num_heads head_dim", num_heads=self.num_heads)
        
        q = rearrange(q, "... seq heads head_dim -> ... heads seq head_dim")
        k = rearrange(k, "... seq heads head_dim -> ... heads seq head_dim")
        v = rearrange(v, "... seq heads head_dim -> ... heads seq head_dim")
        
        seq_len = q.shape[-2]
        mask = torch.triu(torch.ones(seq_len, seq_len, dtype=torch.bool, device=in_features.device), diagonal=1)
        mask = mask.unsqueeze(0).unsqueeze(0)
        
        scores, out = self.scaled_dot_product_attention(q, k, v, mask)
        print(out.shape)
        
        out = rearrange(out, "...  num_heads sequence_length head_dim -> ... sequence_length (num_heads head_dim)")
        out = einsum(out, o_proj_weight, "... sequence_length d_v, d_model d_v -> ... sequence_length d_model")
        return out
    
class CausalMultiHeadAttention_(torch.nn.Module):
    """
    CausalMultiHeadAttention 是因果多头注意力，它通过将输入的稠密向量与输入的稠密向量进行点积来得到输出。
    每个头的公式都是：
    out = softmax(QK^T / sqrt(d_k))V
    Args:
        d_model (int): 输入的维度，也就是d_model
        n_heads (int): 头的数量
    input:
        x: (batch_size, seq_len, d_model) 输入的稠密向量
        wq: (d_model, d_k) 查询的权重
        wk: (d_model, d_k) 键的权重
        wv: (d_model, d_v) 值的权重
        wo: (d_model, d_model) 输出的权重
    output:
        out: (batch_size, seq_len, d_model) 输出的稠密向量
    """
    def __init__(self, d_model, n_heads):
        super().__init__()
        self.d_model = d_model
        self.n_heads = n_heads
        self.head_dim = d_model // n_heads

    def attention(self, Q: torch.Tensor, K: torch.Tensor, V: torch.Tensor, mask: torch.Tensor | None = None):
        d_k = self.d_model
        scores = torch.matmul(Q, K.transpose(-2, -1)) / torch.sqrt(torch.tensor(d_k))
        if mask is not None:
            print("scores.shape",scores.shape)
            print("mask.shape",mask.shape)
            scores = scores.masked_fill(mask == 0, -1e9) #如果mask为0，则将对应位置的score设置为-1e9
        attn_weights = torch.softmax(scores, dim=-1) #对key这一维度进行softmax归一化
        return scores, torch.matmul(attn_weights, V) # 将attn_weights与value相乘得到最终的输出
    def forward(self, wq, wk, wv, wo, x)->torch.Tensor:
        batch_size, seq_len, d_model = x.shape

        q = x @ wq.T # (batch_size, seq_len, d_model) @ (d_model, d_k) -> (batch_size, seq_len, d_k)
        k = x @ wk.T # (batch_size, seq_len, d_model) @ (d_model, d_k) -> (batch_size, seq_len, d_k)
        v = x @ wv.T # (batch_size, seq_len, d_model) @ (d_model, d_v) -> (batch_size, seq_len, d_v)

        q = q.view(batch_size, seq_len, self.n_heads, self.head_dim) #view会优先切分最后一个维度，这和内存有关。
        k = k.view(batch_size, seq_len, self.n_heads, self.head_dim)
        v = v.view(batch_size, seq_len, self.n_heads, self.head_dim)

        q = q.transpose(1, 2)
        k = k.transpose(1, 2)
        v = v.transpose(1, 2)

        #现在的形状是(batch_size, n_heads, seq_len, head_dim)
        # 创建mask，用于防止当前位置的token看到未来的token。
        mask = torch.triu(torch.ones(seq_len, seq_len,dtype=torch.bool,device=x.device), diagonal=1)
        mask = mask.unsqueeze(0).unsqueeze(0) # (1, 1, seq_len, seq_len)

        scores, out = self.attention(q, k, v, mask)
        print(out.shape)
        
        out = out.transpose(1, 2)
        out = out.contiguous().view(batch_size, seq_len, d_model)
        out = out @ wo.T
        return out

In [10]:
wq = torch.randn(64, 64)
wk = torch.randn(64, 64)
wv = torch.randn(64, 64)
wo = torch.randn(64, 64)
a = CausalMultiHeadAttention(64, 4)
b = CausalMultiHeadAttention_(64, 4)
x = torch.randn(4, 12, 64)
o1 = a(wq, wk, wv, wo, x)
o2 = b(wq, wk, wv, wo, x)

torch.Size([4, 4, 12, 16])
torch.Size([4, 4, 12, 16])
scores.shape torch.Size([4, 4, 12, 12])
mask.shape torch.Size([1, 1, 12, 12])
torch.Size([4, 4, 12, 16])


In [11]:
o1 == o2


tensor([[[ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         ...,
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False]],

        [[ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         ...,
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False]],

        [[ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         ...,
         [ True,  True,  True,  ...,  True,  True,  True],
         [

In [12]:
import torch
mask = torch.tril(torch.ones(5, 5)).bool()
s = torch.randn(5, 5)
s.masked_fill(~mask, float('-inf'))

tensor([[-1.4897,    -inf,    -inf,    -inf,    -inf],
        [ 0.8726,  1.5124,    -inf,    -inf,    -inf],
        [-2.0606, -0.7163, -1.1043,    -inf,    -inf],
        [ 0.4053, -0.5487,  2.7519, -0.6709,    -inf],
        [ 2.8074, -2.1857, -0.0755, -0.7039,  0.2653]])

In [1]:
import os

# 获取逻辑CPU核心数（包括超线程）
logical_cores = os.cpu_count()
print(f"逻辑CPU核心数: {logical_cores}")

# 在Unix/Linux系统中，还可以获取物理核心数
if hasattr(os, 'sched_getaffinity'):
    physical_cores = len(os.sched_getaffinity(0))
    print(f"当前进程可用的CPU核心数: {physical_cores}")

逻辑CPU核心数: 56
当前进程可用的CPU核心数: 56


In [7]:
files = ['valid_temp/chunk_8.txt', 'valid_temp/chunk_9.txt', 'valid_temp/chunk_10.txt', 'valid_temp/chunk_11.txt']
print(sorted(files, key=lambda x: int(x.split('_')[-1].split('.')[0])))

['valid_temp/chunk_8.txt', 'valid_temp/chunk_9.txt', 'valid_temp/chunk_10.txt', 'valid_temp/chunk_11.txt']


In [6]:
'12_34_43'.split('_')

['12', '34', '43']